include:
  - local: "/.gitlab/ci_templates/includes/cache.yml"
  - local: "/.gitlab/ci_templates/includes/task-type.yml"

.step-build:
  extends: .task-type-cargo
  cache:
    - !reference [.caches, cargo-cache, readonly]
  artifacts:
    paths:
      - "target/debug/*"
  script:
    - apk add --no-cache build-base musl-dev openssl-dev openssl bash zlib-dev zlib-static
    - cargo build
